services:

  webapp:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
      - "8888"
    ports:
      - "3000:3000"
      - "8888:8888"
    volumes:
      - .:/app
    command: /app/entrypoint.sh
    environment:
      CHOKIDAR_USEPOLLING: true
      FAST_REFRESH: true
      REACT_APP_CURRENT_ENV: production